//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadDuLieu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gold
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public Nullable<double> SoldOut { get; set; }
        public Nullable<double> BuyInto { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Content { get; set; }
    }
}
