//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadDuLieu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinHieuPost
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Content { get; set; }
        public Nullable<double> TP { get; set; }
        public Nullable<double> SL { get; set; }
        public string Image { get; set; }
    }
}
